### PR TITLE
Add Paginator and PaginatedTable stories

### LINKED ISSUE #19: add storybook tests to Paginator and Tabs shared components

### PR DESCRIPTION
**Pull request by guieiras**
Closes #19

Hello! Me again. As my first PR (#23) was merged, I added this to complete issue resolution.

### CODE REVIEW

**Comment by guieiras** [comment]
I would be very grateful if you can add the label `hacktoberfest-accepted` on this PR. Thanks :D

**Comment by shootermv** [comment]
Thank you again. 
Your pr is great, but it better to contain single commit. 
Do you know how to squash commits? If not - i will be glad to guide you
Thanks

**Comment by guieiras** [comment]
Of course! I’ll squash it.

**Comment by guieiras** [comment]
@shootermv Done! I've squashed all commits into https://github.com/shootermv/follow-favorite-repos/pull/25/commits/45416c9738b9a96e1fcb0c86b26950a4aa86596d

**Pull request merged**
